version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8000:80/tcp"
    environment:
      TZ: "Pacific/Auckland"
    volumes:
      - '/data/pihole/etc:/etc/pihole'
      - '/data/pihole/dnsmasq.d:/etc/dnsmasq.d'
    #cap_add:
    #  - NET_ADMIN
    restart: unless-stopped
