version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    ports:
      - "8123:8123/tcp"
    environment:
      TZ: "Pacific/Auckland"
    volumes:
      - /data/home-assistant/config:/config
      - /data/home-assistant/etc:/etc
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    cap_add:
      - CAP_NET_RAW
      - CAP_NET_BIND_SERVICE
